import { TheFooter } from '@/components/TheFooter'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { TheHeader } from '@/components/TheHeader'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* тут отключаем шрифты, если не нужны */}
      {/* <body className={inter.className}>{children}</body> */}
      
      <body>
        <TheHeader/>
        <main className='container'>{children}</main>
       
        <TheFooter/>
        </body>
    </html>
  )
}
